issuer: https://token.actions.githubusercontent.com
subject: repo:amouat/production-builds-with-renovate:ref:refs/heads/main

permissions:
  checks: write
  contents: write
  issues: write
  members: read
  pull_requests: write
  statuses: write
  workflows: write
